name: Check if bot starts and stops correctly

on: push

env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}

jobs:
  start-stop-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check if bot starts and stops correctly
        id: start-stop-test
        env:
          STATUS: ""
        run: |
          chmod +x .github/workflows/scripts/run.sh
          .github/workflows/scripts/run.sh
          echo "STATUS=${STATUS}" >> $GITHUB_ENV
        shell: bash
      - name: Check status
        run: echo "Status:${{ env.STATUS }}"
